---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    token: AgC/46Yk+RDlV8HqT5dOgTwBPTB1yvkVALN7bcQgVxjhluomPArmWvwXp9tO9Ckk4lUQ3V+dSlSYZjoMo0mlA35qESfvC2D+T26SnbKWPIqycDrX+eAt6hbC6QQLzSzvQyuAag1FwZPcNfWUX/3EdpnZ6zxYW2BFKUkRh/wORI4uGw96mafjf63Ft9qls4+TQk1K8JOoD7aoeXBhqP7EXFNWjWRchRGsz5z6ftihzQSgmRBlqxy5DGLTkmudddOo/4Eog/vAEYu5DSFRUsVt4WE7/vXQKEejJx+hIQ08uwqqNSuy9Q9Cd8y9eORNgKlJrhSynMg0h4T9B1X5RdJKIVdbE+34BaSnhSx/u2c+euwxgtTGNx0J9e/xv7t8+1RzYqkLa2AT/NP1qms7KjsuIPcbHYJ01KX9+1+kdFc/4qmrHoVDc1LRSU/Q8fBK1TiismjfPt/xYioZMl7qwtdUnjdZm2QKWh386PfaKRdG3gciTfsCLDm8pvd57DHttiZZlUUV2pwdLeUK5y0DnGCf0Io4p450PI5pbG6102DOsiOh/pVzEyhOxUCJ1IswEwscsLKAyZcUWlSdG1OeJu568VtilF0groOjLoFWmQlNGn0NDORkqsuXPoaI+RB9APgmIZRXfWlEhRdjf1UJLcrlZ2C4b7GAOpsQDBgTMwC4K0BCOSJcShH1/j4MiPwsiEAowTg2s40qEWogHy1xU3PEipZVrHS44F7BVrK1I0RBDVV3Hkh0Z/JYmMfhYkQZUgtFp+c/8G75BpVgLRZc03J6UDpKOxYHFh7UVgjdQNPaPEbiK6KWxcfTBK1UWroCn3Dlu2lQ8QgA3cp0rz5B4xHPHuD5nIx+R6JpvfBOubANqc7pJGjsre0GuYyNjlpWkbGmbj/3E/28ju0lNq5KNRz8igBFOTcO4zGbdqEFVOlemFwQlsQftuCUZHGl
  template:
    metadata:
      name: cloudflared-secret
      namespace: cloudflared
