---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCVCbkldUs0VKGnAZklDgRV6BDK+Ov1ovayu4SFsHl4H/a/nR0s5b5ZUIB+vhNsYyrzNx+sz8D8vWyu0hJODeWzNroCZigGneW0e3pI/uqaOeKQNYVZf3gVAUv+maqNKmO1us7s49dbmwsjG3KP5VmPLkPwPhFiI6tkf9GN1x6xxVoYV9+tZoTO0sJh8TK4bMj+JOIeTVjAcTlRtfVPyA7jrMMj/ldlgEAyseaafPq5ldHPRZVFecUjHApZrB+2tmREs69xjpci8MRrQX9gzKYiHqPZdX4MGJQSHrEjw7BSHoTj4DheOTWBsqhCTgmoMIJOXy5BzpfMH1lTopIoexRQjtLCJ5zEeRo7bmtLdGI97lqj+EIYnwvSUqbBLp88JGSUH/Ywr7vdAODFoseVDkrA8AkdLfVc0eQKY2dVNCUbCeDHB0BWao+svxy49uQeuORC8sqsMFDDKP15/wakYdY7nw1gcddXu4oUvpAbsjXmiS2PYpey/guTcHHfpUjNI1DT6RkXdT9Q3bH9zpw2kbmUOOmn+tZEab/qRgEv2mB7oHMzw1pD8rKA1pi1AE0BXZN4vbMkkmo5wmQnWJ0FpyOKKvMdb99W+YM4y7bSHhdBGPausWhkHXFF5WAHUQryaVQO/u/ZA00ekUiK9fFJtUJxgo5M/vujcu9qd7p3rxBp+/cBBnC/7xhmHdhd7aIsomjQV/q1UysWuVx9nBU6f9MfyNCgiu0Oc2j9ndQYWp3hhMtgZan6tE9zsBqzasEFyM0oM932DKwG01owo0JSPxAIZhdIJTTRmcwgbEnZ91Ojj0Yk8s9BdTEM+R0bCZLO/b8kn7ImJvpkApdl4PPg3QjiD5VO4Ja3UIEI54uyxG36mWSnjSiVLw6eiMbgWKCvA/t3XOcR34aidEMYKsqU2XXtJWSmgINvlUgqRRDglvCjwo0kzm6aS3xb
  template:
    metadata:
      name: cloudflared-secret
      namespace: cloudflared
