---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCSoQIJajiIrcDy4RZg134Gom5UiHxXuWiVnk0coaBh1wGzvO7+LTBRu0RY6CR9maoCLt59c446Oiuj/EyDTLGagIkRfbmspsCIrY+VyUxczS645oQvvwPkS0p19hJPaMtruh2DRniZSi+ncumaL5vTlLadtZSjzP2cW/Jn6sJx12igg/Do+JPYDhDjVL1PZ0WhNXafd1CW9xicS0a7Q1NCwzHRhHNx6ptv/j60Tj5yAKkbj7vvn5028iJWSkHuHp0jAnYqspToVOUKaMwmj84LwDuzs8aPkSoRQiVpTVPl5N7qRSQqE3DSkZybFkZEQUrbwaqrp/oe6qmAEAjvClmmfNyKo98cUOxucyEIyCVYg39NjbZtxDcp+ssaJ3AS5vbby0+mHl08ppyDGWSdMak64kCHivSFUp60ofNKiecQTen9KNVnTNbFPodJhnD5E9rcZl944NS+9lWNXeerYTRR4xOdlpFEzzmvbtbjkoQedqQdq6N6Z5ab3DsotM+SBo4eGMyoWl4/RNpLz5Vmw5cporDUNLZxQzAw+Jh+9OTsRWJIY6fTbE9MKfQ3OCwCNFqWbMYnoo+nTpXvd4kfk7H2BuN5lHDcSEdesSt7jnEaoaI7AlpnuDkDJtHC0xGoOwhw3/Boysp//Sc/eJxWBi74ufS2OyvdE6nlCTcaBpipNlRE6e+ug3H/kWoxJYDITItRkHMTINVnZnE2sf1EaLveKRgyOrpoOXnBs5ByiFQcRjboThZhYjpE
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
