---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: '1'
spec:
  encryptedData:
    api-token: AgBnhqwyOWsDrKQ8sKataAkgy+RIPBy8Y9P2gShnUVyikKFVVPLaPQsGpE5y81aJWj8IJsuw9NakQ80tN9Z8vxChIgeKzIuiMmMw2WvH+mTnbWosDY9C1jnX8kYF2LrTE6BJP9AKYTQu2NIO4DQdM4gbr+e8Xo5xV0PBFI6uIBNuYu7Gm2WQmoE7+kiWWE8PFFSJnTxeiKWAJNakunoCmnXbR5oUa4L+omxewjuNDIz2KAxEwIv9IA9qv/NjaaG0ez9fLHvVK5AGUjMQuEUkWdVIdu4U3DZ0316fCotRMhcLFbWnk5Cyy3Kony+IQOBmnollqLKqeeOJkMqZNWxUykwXWmBe20VH/T1u3dHJYad3rwNHmWDf7sgFt8I46sqkxIf/TzJvaNa/TWv6O/O5mfDfgPyZQnrKrz4nMcx/jo1hHhCzAe0KrKfaeTHXCycyZvDd3gq8pQR3NIIweczMUf0v0naTtdzICCBukXzZezd1emYfhDyEuHX8gWgocyh603RP7nyqlikE73z2sf5krbrG8t5TDyNw2AveN7esUsMwJI5HfLa9MGVornYqwOEyfpE998zNyJARcx5yCPM1x1rYsRK25x3ON0wx6z7rbKkt+6dZ12oPH+tTQY+0gG+mCCM0C9CV0D8cu5AnydQgRrdcMT7O1sgyTgVfj3jnrXyQ4Nn+1E27oRh6y5tK209ufHXh+DmAoM7wq4/jbMaeg5JtEQjBDtpSd7FiCur+xCBxBP7vqNHVI2nc
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
