---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: '11'
spec:
  encryptedData:
    api-token: AgAWF1QD9puOpKhUjC6CH75Vpq15+mAKTrze2D3Ego3YPh2qXKoNr4eRgIKUGXzGuW9c0CKa47u7Eoo/9RV/K1opK9mA/fOKAaIvNBoARy+1Q/784FBegBilKJ2zEUo83oGwtlm30Q/oh3TyE3HiIjEf0NMj0OkiyWKq/WGW3Rqy7bzI4NQifHjXS/Q4u7ECe6kP7agtNODtu4mTR4LTJfM1e8HgThaVnutQCvKRb53RHgauUgSpaZDCmuVYS+47VyXIk7iYx8reFy3Lq7zWJQheqqhrz2vDCNA8jdPpKxY6urne/WJ7exyMFynFmoEZuDZZdm160ndBh2t0FklNUq0gKmAnDeai3DEgBjSR647Cmc8IpVTvyYxH7HBHyGkwlYJFg0KrgyF2Jb6lrg2HwwEXcXTSKhgX76xiJJ7yCQrpupKEitRApNwV3mM4oqkIbYomKNUsDz6diRg5pYHfs17c1xxcRU/8eAM2h5o9bxdFkKi1PYz3ecqBnCURP/9rE6ZiFpDxazUKUi5HhD/RlFDibMr9BInIc1DSb51NBBAtVqjPip0xwbxi3Lu4aOV39++s/71/TXVHcijGxo9vdaXVyZQoBgYL3Tv8vbF7cDouMi4VH83H3TqPJEHYCiookGrDkLqAkadM1xA7n/rdivNrsXNOohDCFr9W2cW2BNFtgrbR/VFRvMr+X8KJMY3e/S+MCj22S8RXll+wnQFIUhZalv+vsFuRdyTuTdohMFyCPq2yptMbtqaT
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
